### ISSUE TITLE
Lines break up when word wrap is used

### ISSUE THREAD

**Issue by mybearworld** [oderwat/vscode-indent-rainbow#158]
Enable word wrap.

#### Expected behavior

![the lines being joined](https://github.com/oderwat/vscode-indent-rainbow/assets/130385691/a4a70e6a-8f3f-427f-8c93-efe435c489cd)

#### Actual behavior
![the lines being broken up](https://github.com/oderwat/vscode-indent-rainbow/assets/130385691/fbc85701-ee83-41ea-8abb-23b7b20f9c8b)

**Comment by oderwat** [comment]
That is the expected and correct behavior, as there is no indentation in this line.

**Comment by mybearworld** [comment]
VSCode will keep the indentation the same for word wrapped lines.
![image](https://github.com/oderwat/vscode-indent-rainbow/assets/130385691/9e8b48df-9f2a-4508-b6b8-800f7da4f775)
```py
if True:
    while True:
        print("This is a very long string that will get separated up by word wrap.")
```
While yes, this would theoretically mean in the middle of the line, visually it's the same line, and still the same indentation level. So it'd make sense to also mark it.

> I wonder how your "Expected behavior" image was created.

Image editing.

**Comment by oderwat** [comment]
The indentation of the line can be by definition only at the start of the line. Your line continuation does not count as an indentation for this plugin.

> Image editing.

Yeah, I figured that. My question was more related to the authority that decided about the "expected behavior". It is what you expect, and your expectation is wrong for what this plugin does. I believe I got a similar request before. But most of the 5.5 million installations seem to share my expectation (or don't care).

**Comment by GBR6000** [comment]
@oderwat I personally would prefer the behaviour describe here. In #57 it makes sense to not colorize but this is different. I use the lines as an indicator of what range of code is going to get folded and so the colouring being non-continuous doesn't make sense to me. Also I think it looks worse. So an optional toggle might be nice. Obviously if it is needlessly complex to add due to the text wrapping not actually containing characters don't bother.

**Comment by oderwat** [comment]
I would not want it even if the VSCode API could do something like that. This indentation is not relevant for the code functionality, and it would harm not to see that it actually is not the indentation of the line itself. I think people who actually were originally targeted with this: Python, Haskell, Nim, Yaml and the ones that I have forgotten would also not like it because it would make reading code harder. This plugin was never about "beauty" even if people like it for that (I suppose). It was created, so you can indent and check your "code indentation language" with less cognitive burden.

**Comment by oderwat** [comment]
> Obviously if it is needlessly complex to add due to the text wrapping not actually containing characters don't bother.

If you make a PR I consider adding it as optional functionality. We had this before for other things I didn't need myself. I also cannot get tired of telling everybody and his dog, that, despite 5.6 million "installations" I got about 40 coffees from this.

**Comment by mybearworld** [comment]
I'd argue it's actually a functionality problem, as these are styled the exact same way as when indentation stops.
