### ISSUE TITLE
python combination of tab and spaces showing up with an error

### ISSUE THREAD

**Issue by eskhool** [oderwat/vscode-indent-rainbow#24]
In whitespace sensitive languages like Python, besides using only spaces or only tabs there is a mixed use alignment formatting style which goes like below

```
line1
<tab>->indent1
<tab>-><s><s>indent1+space to align with content above
```

this is being detected as mixed presence of tabs and spaces.
any suggestions or take as an enhancement request?
basically if the tab indent is same as the line above then allow arbitrary spaces after that ...it could be a preference to be enabled for languages

**Comment by oderwat** [comment]
The error indicator is meant to highlight such cases. You could simply switch it off.

**Comment by eskhool** [comment]
Sure but that takes away the benefit

Ideally I would like the error indicator to spot a hidden tab embedded in the middle after spaces
for eg.

for instance
GOOD
tab tab
tab tab < n spaces> 

BAD
tab tab
tab tab < n spaces> tab

**Comment by eskhool** [comment]
Not to get into the holy war about tabs and spaces or (gasp) tabs+spaces =). Not clueless here, have seen and read PEP8. Python3 works just fine with this combination (forbid?). We use this for the following simple reason:

If you like tabs for your code indentation (as opposed to fixed number of spaces) because it works as per the developer preference of IDE/terminal ... only problem that remains is that when you view the code over SSH then the multiline continuations done via tab don't align up on different tab sizes.

def abc:
<TAB>some_variable = <<an unusually long line since I don't feel like writing real code>>
<TAB><SPACESSPAC><<unusually long code continues aligned below the above>>

Now you may still not be convinced (personal choice and respected)...however a quick pointer to where to start with this would help. just don't want to dig from scratch into a new codebase.

Performance won't end up mattering as it will be a switch so excluded from the other code paths presently used for the checks

**Comment by oderwat** [comment]
If you always only want to test for tabs and ignore spaces after them, you could change the pattern here: https://github.com/oderwat/vscode-indent-rainbow/blob/master/extension.ts#L167 

I think when you remove the space from this pattern, it will do what you want.

The other way would be changing https://github.com/oderwat/vscode-indent-rainbow/blob/master/extension.ts#L211 with some code/test which obeys your rules.

**Comment by eskhool** [comment]
thanks. sounds straightforward enough.
saw something interesting in the code base and then verified the 'bug'...if the number of spaces  is divisible by tab size then it no longer reports this as an error even in a tab aligned file...that is an interpreter/pylinting error in any python being missed.
I assume this is because you are not a tab user at all? Should I feel free to make the PR take care of such issues too or would you like to address that and I can work on top of that change?

**Comment by oderwat** [comment]
As you may see in the code the TAB/SPACE equivalence is by design. And this can also be seen as what is correct when mixing TAB and SPACE in this editor (where no real TABs are available). If it is aligned to the same total length it is OK - by design.

I use all kinds of whitespace depending on language and project. That there are different views of what can be considered as "error" is not surprising.  It does not depends on personal views, it depends on what the reality is. Having >100.000 installs of this plugin is what surprised me. This may indicate that I managed to have sane defaults for "most" people. But one can't be sure.

I personally still don't think that having more "error" options is an extension which is needed. For errors or warnings like this I use integrated syntax / lint checkers for the language I use. Those tell me if my indentation is valid or not. So disabling the error line "odd" spacing is usually all one needs to do.

**Comment by eskhool** [comment]
Fair enough. Though 'most' of the world believe in one religion/god or the other. Does that make them right? :-)

We have flake8 doing this for us but your colors looked cooler and since you did get the majority and that's why I was looking to enhance this plugin to make it work for us. 

Cheers.
